- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disable old nodejs and enable new nodejs
    ansible.built.command: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: node js
      state: present  
  - name: create roboshop user
    ansible.buitlin.user:
      name: roboshop

  - name: Recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: directory
      
  - name: ansible app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: download catalogue application from remote
    ansible.buitin.get_url:
      https://roboshop-builds.s3.amazonaws.com/catalogue.zip
    
  - name: extract catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  
  - name: install dependecies
    ansible.builtin.command: npm install
    args:
      chdir: /app
  - name: copy catalogue service
    ansible.builtin.copy:
      src: catalogue.service
      dir: /etc/systemd/system/catalogue.service

  - name: deamon reload and start
    ansible.builtin.systemd_service:
      daemon_reload: true
  
  # lets start after daemon reload

  - name: copy mongodb.repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repo.d/mongodb.repo
  
  - name: install mongodb client
    ansible.builtin.package:
      name: mongdb-org-shell
      state: present

  

